<?php
	defined('BASEPATH') OR exit('No direct script access allowed');
	
?>
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h2>Terms and Conditions</h2>
            <div style="height:400px; overflow:scroll;">
                <p>THIS IS A LEGAL AGREEMENT. BY ACCESSING THIS WEBSITE AND/OR PURCHASING ANY PRODUCT ON THIS WEBSITE, YOU ACCEPT AND AGREE TO BE BOUND BY ALL THESE TERMS AND CONDITIONS. PLEASE READ THIS ENTIRE AGREEMENT CAREFULLY BEFORE CONTINUING USE OF THIS WEBSITE OR BEFORE PURCHASING AND/OR USING PRODUCTS ON THIS WEBSITE.</p>
                <h3>1. Parties.</h3>
                <p>This Agreement is entered into between any visitor to this website and any party purchasing products listed on this website ('User'), and this web site, owned and operated by www.myclick123.com All references to 'the company', 'this website' or 'this site' shall be construed to mean www.myclick123.com</p>
                <h3>2. Agreement To Terms of Use And Amendment.</h3>
                <p>In addition to these generally applicable Terms and Conditions, the prepaid telecom service (the 'Service') on this website is subject to specific terms, rates and/or rules ('Product Information'). Any reference to this Agreement or these Terms and Conditions incorporates the contents of the Product Information applicable to specific Products. By accessing this website, purchasing and/or using the Services, User agrees to be bound by and accepts these Terms and Conditions, as well as the Product Information applicable to each Service, as such Terms and Conditions and Product Information may be changed and updated from time to time. Specifically, all rates listed in the Product Information are subject to change. Company may amend these Terms and Conditions from time to time without notice to User. User should periodically check this website for any changes to the Terms and Conditions which will be posted with the new effective date. If User does not agree to be bound by this Agreement, User must discontinue use of this website.</p>
                <h3>3. Customer Service.</h3>
                Contact information, including customer service contact information is available at myclick123@hotmail.com
                <h3>4. Refunds and Exchanges.</h3>
                <p>www.myclick123.com is a prepaid telecom service retailer. It purchases the Services sold on this website from telecommunications carriers who create and service those Products. In the unusual event that performance issues arise with a Service sold on this website, or that User does not receive the specific rates advertised for a Service sold on this site, it is the carrier's responsibility to provide an adequate remedy. If a carrier is unable to provide a satisfactory remedy, Users must contact www.myclick123.com within thirty (30) days of the original purchase date to begin an inquiry.www.myclick123.com will intervene on the User's behalf with the carrier to have the Service or lost minutes promptly replaced, or will provide you with additional minutes to make up for a defect unresolved by the carrier.www.myclick123.com’s guarantee applies only to User's most recent purchase.www.myclick123.com will not refund time or money for subsequent purchases of the same Service. If User's experience with a particular product has proved unsatisfactory for a particular country, international cell destination, or otherwise, please do not purchase or recharge that product.www.myclick123.com’s guarantee is limited to the original retail purchase and is non-transferable. Warranty claims must be made within thirty (30) days of purchase.</p>
                <h3>5. User Responsibilities and Privacy Policy.</h3>
                <p>The Services on this website are only available to individuals who can form legally binding contracts under applicable law. To legally purchase the Services on this website, in compliance with these Terms and Conditions, User must providewww.myclick123.com with User's legal first and last name, billing address, city, state, country, postal code, and e-mail address. Should User knowingly falsify any of the required information, User's account shall be terminated immediately with or without prior notice. User should make every reasonable effort to safeguard its user name and password from unauthorized use.www.myclick123.com is not responsible for any unauthorized use of User's account.www.myclick123.com has the right to terminate User's account at any time if company has any reason to believe that User has misused its account.</p>
                <h3>6. Prohibited Conduct.</h3>
                <p>User agrees not to use the Services on this website for illegal purposes. User agrees to comply with all applicable laws and regulations of any applicable governmental entity, as well as the policies and procedures of the underlying telecommunications carriers which provide and service the products on this site. Credit card fraud is a criminal offense.www.myclick123.com uses automated and manual systems to confirm proper credit card authorization.www.myclick123.com also tracks every transaction. Information related to fraudulent transactions, including but not limited to IP addresses, detailed call records, transaction data and email addresses is collected and will be provided to appropriate law enforcement officials consistent with applicable law when required to assist in the prosecution of any persons attempting to commit fraud on the website.</p>
                <h3>7. Indemnification.</h3>
                <p>User agrees to release, indemnify, defend and hold harmless www.myclick123.com, its subsidiaries, affiliates, officers, directors, employees, agents and advisors, from and against any and all losses, liabilities, claims (including claims without legal merit or brought in bad faith), demands, damages, costs or expenses, causes of action, suits, proceedings, judgments, awards, executions and liens, including reasonable attorneys' fees and costs (whether brought by third parties or otherwise) (collectively, 'Claims') due to or arising out of User's purchase of Services on this website and/or use of this website.www.myclick123.com reserves the right, at its own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by User hereunder, and in such event, User shall have no further obligation to provide indemnification for such matter.</p>
                <h3>8. Representations and Warranties.</h3>
                <p>THIS WEBSITE AND THE PRODUCTS ON THIS SITE IS PROVIDED 'AS IS' AND 'AS AVAILABLE' WITH NO REPRESENTATIONS OR WARRANTIES OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, SYSTEM INTEGRATION, TITLE AND NON-INFRINGEMENT. IN PARTICULAR, BUT WITHOUT LIMITATION,WWW.MYCLICK123.COM DOES NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED OR ERROR-FREE, THAT DEFECTS WILL BE CORRECTED, OR THAT THIS SITE OR THE SERVER THAT MAKES IT AVAILABLE IS FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. WWW.MYCLICK123.COM DOES NOT WARRANT OR MAKE ANY REPRESENTATIONS REGARDING THE USE OR THE RESULTS OF THE USE OF THIS WEBSITE OR THE PRODUCTS, IN TERMS OF ITS CORRECTNESS, ACCURACY, TIMELINESS, RELIABILITY OR OTHERWISE. USER UNDERSTANDS AND AGREES THAT IT ASSUMES TOTAL RESPONSIBILITY FOR ITS USE OF THIS WEBSITE AND THE PRODUCTS ON THIS WEBSITE.</p>
                <h3>9. Limited Liability.</h3>
                <p>WWW.MYCLICK123.COM AND ITS AFFILIATES AND CONTENT PROVIDERS AND THEIR RESPECTIVE SHAREHOLDERS AND AFFILIATES SHALL NOT BE LIABLE FOR ANY LOSS OF BUSINESS, LOSS OF USE OR OF DATA, INTERRUPTION OF BUSINESS, LOST PROFITS OR GOODWILL, OR OTHER INDIRECT, SPECIAL, INCIDENTAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES OF ANY KIND ARISING OUT OF THIS AGREEMENT, EVEN IF THEY HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH LOSS AND WHETHER OR NOT THEY HAD ANY KNOWLEDGE, ACTUAL OR CONSTRUCTIVE, THAT SUCH DAMAGES MIGHT BE INCURRED, AND NOTWITHSTANDING ANY FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY. THIS EXCLUSION INCLUDES ANY LIABILITY THAT MAY ARISE OUT OF THIRD-PARTY CLAIMS AGAINST USER. USER FURTHER AGREES IF USER BECOMES ENTITLED TO ANY RECOVERY, THAT ITS RECOVERY SHALL BE LIMITED TO THE AMOUNT OF FEES OR PAYMENTS MADE TO, WWW.MYCLICK123.COM IF ANY, FOR THE PRODUCT AT ISSUE.</p>
                <p>WWW.MYCLICK123.COM WILL NOT BE LIABLE FOR ANY FAILURE OF PERFORMANCE DUE TO CAUSES BEYOND ITS CONTROL, INCLUDING, BUT NOT LIMITED TO, ACTS OF GOD, FIRES, FLOODS OR OTHER CATASTROPHES, NATIONAL EMERGENCIES, INSURRECTIONS, RIOTS OR WARS, STRIKES, LOCKOUTS, WORK STOPPAGES OR OTHER LABOR DIFFICULTIES, PREEMPTION OF EXISTING SERVICES IN COMPLIANCE WITH ANY LAW, ORDER, REGULATION OR OTHER ACTION OF ANY GOVERNING AUTHORITY OR AGENCY THEREOF.</p>
                <p>EXCEPT AS SPECIFICALLY PROVIDED IN SECTION 4 HEREIN, WWW.MYCLICK123.COM WILL NOT BE LIABLE FOR ANY ACT OR OMISSION OF ANY COMPANY FURNISHING A PORTION OF THE SERVICE OR OF ANY THIRD PARTY, INCLUDING THOSE VENDORS PARTICIPATING IN OFFERINGS MADE TO USER, OR FOR DAMAGES ASSOCIATED WITH SERVICE, CHANNELS, OR EQUIPMENT THAT IT DOES NOT FURNISH, OR FOR DAMAGES THAT RESULT FROM THE OPERATION OF CUSTOMER-PROVIDED SYSTEMS, EQUIPMENT, FACILITIES OR SERVICES THAT ARE INTERCONNECTED WITH WWW.MYCLICK123.COM SERVICES.</p>
                <h3>10. Dispute Resolution/Applicable Law.</h3>
                <p>No dispute or claim may be brought as a class action or as a private attorney general, and User will not have the right to act as a class representative or participate as a member of a class of claimants with respect to any dispute or claim. No waiver of the Terms and Conditions is valid. The Terms and Conditions are binding upon User and www.myclick123.com and upon, respectively, User's and www.myclick123.com’s agents and heirs. If any part or provision of these Terms and Conditions is finally determined to be invalid or unenforceable under applicable law by a court of competent jurisdiction, then that part or provision will be ineffective only to the extent of such invalidity or unenforceability, without in any way affecting the remaining parts or provisions of these Terms and Conditions, which will still be given full force and effect.</p>
                <p>If User has a dispute concerning the Products, User should first contact www.myclick123.com’s customer service, as specified on the website at  www.myclick123.com. If User is unable to resolve the dispute with customer service, User agrees that the exclusive forum for resolution shall be through arbitration. Arbitration is final and binding. User agrees that all disputes arising out of or related to these Terms and Conditions (regardless as to whether the dispute is based in contract, tort, statute, fraud, misrepresentation, or any other legal or equitable theory) will be submitted to the American Arbitration Association ('AAA'), for final and binding arbitration. For consumers, the arbitration will be conducted under the AAA Arbitration Rules for the Resolution of Consumer-Related Disputes Commercial Arbitration Rules ('AAA Rules'), as such rules are in effect on the date of commencement of the arbitration and as such rules are modified by these Terms and Conditions. For businesses that purchase www.myclick123.com Products, the arbitration will be conducted under the AAA Arbitration Rules for Commercial Disputes, as such rules are in effect on the date of commencement of the arbitration and as such rules are modified by these Terms and Conditions.</p>
                <p>The arbitration will be based only on the written submissions of the parties and documents submitted to the arbitrator, unless the parties agree or the arbitrator orders otherwise. Additional charges may apply for such procedures. The award may be confirmed and enforced in any court of competent jurisdiction. Currently, the AAA Rules provide for reduced filing fees for consumers. Unless otherwise provided for in the AAA Rules or in the arbitration award, all other administrative fees and expenses of arbitration, including the fees and expenses of the arbitrator, will be divided equally between User and www.myclick123.com Each party will bear the cost of preparing and presenting its own case. Any in-person arbitration proceedings will be held in Jacksonville Florida. Each dispute will be arbitrated on an individual basis and will not be consolidated in any action with the disputes or claims of other consumers or customers. No dispute or claim may be brought as a class action or as a private attorney general, and User will not have the right to act as a class representative or participate as a member of a class of claimants with respect to any dispute or claim related to the Products. Any dispute or claim arising out of or relating to these Terms and Conditions must be brought within one (1) year after the date on which the basis for the dispute or claim first arises, regardless of applicable statutes or laws to the contrary.</p>
                <p>These Terms are governed by and construed under the laws of the Jacksonville Florida without regard to choice of law principles. Effective Date: Tuesday July1, 2014.</p>
                <p>www.myclick123.com may make available on through www.myclick123.com or otherwise products and services from other providers, including domestic mobile top-up and international mobile top-up (collectively, 'TopUp'). TopUp is provided by third party companies and operators in various countries that are not affiliated with www.myclick123.com (collectively, 'Third Party Operators').www.myclick123.com merely distributes the TopUp. The terms of use, charges, fees, taxes, credits and expiration policies for TopUp is established and provided by the Third Party Operators.www.myclick123.com shall not be liable for the acts or omissions of the Third Party Operators.www.myclick123.com will not be liable for any disruption, delay or other omissions in the telecommunication and other services underlying the services purchased through TopUp. All purchases of TopUp are final and may not be exchanged, canceled or refunded, except by the applicable Third Party Operator.www.myclick123.com reserves the right to amend and update these Terms & Conditions from time to time in its sole discretion. Users are bound by any amendments or changes posted online. Users should regularly check these Terms & Conditions for their current version.</p>
            </div>
            <form action="" method="post">
                <br />
                <input type="checkbox" name="Ifagree" required="yes" value="1"> I agree
                <br />
                <br />
                <input type="submit" class="btn myRingButton" name="submit_agreement" value="submit">
            </form>
        </div>
    </div> 
</div>    